version: '3'
services:
  redis:
    image: redis:5.0.6
    volumes:
      - redis_data:/data:delegated
  db:
    image: postgres:11.9
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: perma-capture:0.8.1
    tty: true
    command: bash
    environment:
    - DOCKERIZED=true
    volumes:
      - .:/app:delegated
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db

volumes:
  db_data:
  redis_data:
